spring.application.name=livro-service
server.port=8081

autor.service.url=http://localhost:8080
autor.service.endpoint=/autores

spring.datasource.url=jdbc:postgresql://localhost:5432/Livro
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
