spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jbbc:postgresql://localhost:5432/
spring.datasource.name=postgres
spring.datasource.password=miguel30032002
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.application.name=autor-service
